### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Dumka-code** [Cohort6-lab/Cohort-Backend-Dev#9]
### Discussed in https://github.com/Cohort6-lab/Cohort-Backend-Dev/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **Dumka-code** April 14, 2023</sup>
Mr Collins Update/Merge the Reverse_proxy folder and ensure the team proceeds with the devs process
Two folder should be created one foreach servers languages.</div>

**Comment by Collinsoden22** [comment]
Noted, I'll attend to it ASAP
